### ISSUE TITLE
i need help get error u have insta??or discord

### ISSUE THREAD

**Issue by nighttsss** [chiaruy/AutoClicker_20191120#1]

**Comment by chiaruy** [comment]
Can you describe your problem?

maybe you can into my discord room by https://discord.gg/VNTzyP

**Comment by MrScary1** [comment]
> Can you describe your problem?
> 
> maybe you can into my discord room by https://discord.gg/VNTzyP

**Comment by nighttsss** [comment]
the discord not work give me ur username  Night.png#0722

error 

E/AndroidRuntime: FATAL EXCEPTION: auto-handler     Process: com.wonbin.autoclick, PID: 6149     java.lang.IllegalArgumentException: Path bounds must not be negative         at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:47)         at android.accessibilityservice.GestureDescription$StrokeDescription.<init>(GestureDescription.java:254)         at android.accessibilityservice.GestureDescription$StrokeDescription.<init>(GestureDescription.java:229)         at com.chiaruy.autoclick.AutoService.playTap(AutoService.java:83)         at com.chiaruy.autoclick.AutoService.access$600(AutoService.java:14)         at com.chiaruy.autoclick.AutoService$IntervalRunnable.run(AutoService.java:108)         at android.os.Handler.handleCallback(Handler.java:873)         at android.os.Handler.dispatchMessage(Handler.java:99)         at android.os.Looper.loop(Looper.java:214)         at android.os.HandlerThread.run(HandlerThread.java:65)
